# Generated by Django 5.1.6 on 2025-03-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="imagen",
            field=models.ImageField(default="", upload_to="posts/%Y/%m/%d/"),
            preserve_default=False,
        ),
    ]
